name: Build

on:
  push:
    branches:
      - main
    paths:
      - 'bin/*'
      - 'lib/**/*'
      - '**/build.yml'
  pull_request:
    branches-ignore:
      - 'release-please*'

jobs:
  plugin_test:
    env:
      ASDF_RACKET_MINIMAL: true
    name: asdf plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v3
        with:
          command: racket --version
